### PR TITLE
Fix pipeline

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
  - Updated pipeline file `azure-pipelines.yml` to use correct images (hosted runners)
    and correct task for artifacts.

#### This Pull Request (PR) fixes the following issues
None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/35)

### CODE REVIEW

**Comment by johlju** [comment]
Integration tests run now, but seems there is a bug in the resource that make it fail.

**Comment by johlju** [comment]
Fixed the PR to use GitVersion v5 so build phase passes.

**Comment by johlju** [comment]
Looks like there is still a bug in `AzDevOpsProject` unrelated to this change that prevents the tests to pass. 🤔

**Comment by kilasuit** [comment]
@johlju sorry in how long this has taken to get to, 
I am going to merge this and then on another PR work on those failing tests so can get going again with this

**Pull request merged**
