### PR TITLE
Update repo files ready for refactor

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description

Update the repository files to prepare for the larger changes coming.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39)

### CODE REVIEW

**Comment by johlju** [comment]
FYI. I'm gonna switch the default branch back to main otherwise the pipeline wont work. Having another branch is gonna be a pain and just add even more maintenance.

**Comment by dan-hughes** [comment]
I was going to ask why build was not triggering. 

Where is best to discuss this module as a whole? With the changes in #37, it would be good to try and unpick that into smaller PR's.

**Comment by johlju** [comment]
Best would to discuss it in the PR that suggest changes, as those interested in the module can have an opinion. 🤔 But the PR has been worked on for a long time without anyone in community that is using the module has raised any concerns or suggestions, so a few weeks back I assumed it is a general good change and would have just merged it. 🤔

**Comment by dan-hughes** [comment]
It's a pretty large change and most of the tests are not using the dsccommunity conventions or tasks.

I'm not sure how much the module is being used either, I can't find it in the PSGallery. 

Any reason you can see for why azure pipelines are not running?

**Comment by johlju** [comment]
It says 

```
/azure-pipelines.yml (Line: 278, Col: 17): While parsing a block mapping, did not find expected key.
9724
```

**Comment by dan-hughes** [comment]
Just seen it.

**Comment by johlju** [comment]
> It's a pretty large change and most of the tests are not using the dsccommunity conventions or tasks.

Maybe split it up with just one DSC resource with all necessary helper code to make it run so that can be reviewed first. 🤔 

> I'm not sure how much the module is being used either, I can't find it in the PSGallery.

There are no releases or tags in the repo so my guess it has never been used since until recently there was not a pipeline added, and no changes to source after it was added that would have triggered a preview build.

**Comment by johlju** [comment]
Suggest removing the Linux, macOS and PS Core unit tests, let us assume this will be used in Windows only until another PR introduces something else? 🤔

**Comment by dan-hughes** [comment]
> > It's a pretty large change and most of the tests are not using the dsccommunity conventions or tasks.
> 
> Maybe split it up with just one DSC resource with all necessary helper code to make it run so that can be reviewed first. 🤔

That's my initial thought, use it to get CI to pass then it will be much easier for future PR's. 

> 
> > I'm not sure how much the module is being used either, I can't find it in the PSGallery.
> 
> There are no releases or tags in the repo so my guess it has never been used since until recently there was not a pipeline added, and no changes to source after it was added that would have triggered a preview build.

That makes sense.

**Comment by dan-hughes** [comment]
Waiting on dsccommunity/DscResource.Common#134 for HQRM to pass.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39)* status: 0 of 71 files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`build.yaml` line 115 at r4](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39#-OBuWAo31HZ84KdQTod3:-OBuWAo31HZ84KdQTod4:bvhnobr) ([raw file](https://github.com/dsccommunity/AzureDevOpsDsc/blob/372125ae6b1d11478265c13fb11228a84a17b950/build.yaml#L115)):*
> ```YAML
>   ExcludeSourceFile:
>     - output
>   ExcludeModuleFile:
> ```

We should add `- Modules/DscResource.Common` to exclude and modules that is not part of `source` in the built moduled

**Comment by dan-hughes** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39)_ status: 0 of 71 files reviewed, 1 unresolved discussion (waiting on @dan-hughes)
> 
> _[`build.yaml` line 115 at r4](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39#-OBuWAo31HZ84KdQTod3:-OBuWAo31HZ84KdQTod4:bvhnobr) ([raw file](https://github.com/dsccommunity/AzureDevOpsDsc/blob/372125ae6b1d11478265c13fb11228a84a17b950/build.yaml#L115)):_
> 
> > ```yaml
> >   ExcludeSourceFile:
> >     - output
> >   ExcludeModuleFile:
> > ```
> 
> We should add `- Modules/DscResource.Common` to exclude and modules that is not part of `source` in the built moduled

Yes. I've disabled Integration tests for the time being.

Just need to fix code coverage merging.

**Comment by dan-hughes** [comment]
@johlju, this should also be green when it finishes.

Next steps, pick a resource out of the other PR and add the minimum files. But not in this PR.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 50 of 70 files at r1, 19 of 19 files at r3, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39#-:-OBv3upH74vLtTQ-6yX7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`.devcontainer/devcontainer.json` line 4 at r7](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/39#-OBv3WBq-k1nXOMgPUAz:-OBv3WBq-k1nXOMgPUB-:b4gg8td) ([raw file](https://github.com/dsccommunity/AzureDevOpsDsc/blob/afeb9251332416b74589db42da1698e4bc32e652/.devcontainer/devcontainer.json#L4)):*
> ```jsonc
> // README at: https://github.com/devcontainers/templates/tree/main/src/powershell
> {
> 	"name": "PowerShell",
> ```

Looks like tabs in this file.

**Comment by johlju** [comment]
Can you check the tabs in the file (see comment), then I merge it.

**Comment by dan-hughes** [comment]
> Can you check the tabs in the file (see comment), then I merge it.

As in convert it to spaces? Not sure why it did that.

**Comment by johlju** [comment]
> > Can you check the tabs in the file (see comment), then I merge it.
> 
> As in convert it to spaces? Not sure why it did that.

Exactly, convert to spaces if possible.

**Comment by dan-hughes** [comment]
> > > Can you check the tabs in the file (see comment), then I merge it.
> > 
> > 
> > As in convert it to spaces? Not sure why it did that.
> 
> Exactly, convert to spaces if possible.

Done.

**Pull request merged**
