### PR TITLE
AzureDevOpsDsc: Support publish wiki documentation

### LINKED ISSUE #15: AzureDevOpsDsc: Wiki help and examples needs automatically generating
_Logging this issue off the back of the initial PR (#7) so it's logged and not missed..._

#### Details of the scenario you tried and the problem that is occurring
With other DSC Community modules (e.g. `SqlServerDsc`), the Wiki help is generated from MOF schema definitions - Currently this module uses class-based resources and there is no current equivalent to generate this documentation.

There needs to be some functionality added to generate the Wiki.

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- AzureDevOpsDsc
  - Added pipeline support for publish markdown content to the GitHub repository
    wiki ([issue #15](https://github.com/dsccommunity/AzureDevOpsDsc/issues/15)).
    This will publish the markdown documentation that is generated bu the
    build pipeline.
  - Added new source folder `WikiSource`. Every markdown file in the folder
    `WikiSource` will be published to the GitHub repository wiki. The markdown
    file `Home.md` will be updated with the correct module version on each
    publish to gallery (including preview).
  - Updated pipeline file `RequiredModules.ps1` to latest pipeline pattern.
  - Updated pipeline file `build.yaml` to latest pipeline pattern.
- AzDevOpsProject
  - Added description to the comment-based help.
  - Added a validate set to the parameter `SourceControlType` to (for now)
    limit the parameter to the values `Git` and `Tfvc`.
  - Update comment-based help to remove text which the valid values are
    since that is now add automatically to the documentation (conceptual
    help and wiki documentation).

#### This Pull Request (PR) fixes the following issues

- Fixes #15

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31)

### CODE REVIEW

**Comment by johlju** [comment]
@SphenicPaul small one to enable Wiki publish and also limit the property `SourceControlType` to the two valid values (the values will show up automatically in the conceptual help and wiki doc).

**Comment by johlju** [comment]
Integration tests cannot run until merged to main.

**Review by SphenicPaul — COMMENTED** [review]
@johlju  - Sorry for the delay in reviewing this - I've just the 1 comment relating to a grammatical error that looks to have existed before this change but might as well be fixed as part of this.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31#-:-MTHP2EM27r4k2Dy7ewM:bh11qbn)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/Classes/010.AzDevOpsProject.ps1, line 21 at r1](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31#-MTHNz3u0PEJzoJsI7-3:-MTHNz3u0PEJzoJsI7-4:b8bz9ni) ([raw file](https://github.com/dsccommunity/azuredevopsdsc/blob/9c48d91d2094822b4f20c04f5c4d7b99398fbc93/source/Classes/010.AzDevOpsProject.ps1#L21)):*
> ```
> changed
> ```

This should probably be  corrected to `change` (i.e. remove the `d`).

**Review by johlju — COMMENTED** [review]
No worries. :slightly_smiling_face: We are all busy with day jobs. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31#-:-MTHSLXo1hVK1x96t2_b:b-5g57y3)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SphenicPaul)

___
*[source/Classes/010.AzDevOpsProject.ps1, line 21 at r1](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31#-MTHNz3u0PEJzoJsI7-3:-MTHSJla-FejR1qwWC3J:b-896fix) ([raw file](https://github.com/dsccommunity/azuredevopsdsc/blob/9c48d91d2094822b4f20c04f5c4d7b99398fbc93/source/Classes/010.AzDevOpsProject.ps1#L21)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

> ```
> changed
> ```

This should probably be  corrected to `change` (i.e. remove the `d`). 
</blockquote></details>

Done.

**Review by SphenicPaul — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/31#-:-MTHT6XZCkiSgANwHdtM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
