### PR TITLE
AzureDevOpsDsc: Increase Azure DevOps API timeout and other minor fixes (fixes #5, #10, #11, #12 and #25)

### LINKED ISSUE #5: AzureDevOpsDsc: The module conceptual help is not complete
We should modify the module conceptual help

https://github.com/dsccommunity/AzureDevOpsDsc/blob/170504467849fa3eae918b4e9ec1d2b7058205ab/source/en-US/about_AzureDevOpsDsc.help.txt#L10-L23

An example on how it could look like is in https://github.com/dsccommunity/xFailOverCluster/blob/master/source/en-US/about_xFailOverCluster.help.txt

### LINKED ISSUE #10: AzureDevOpsDsc: Built module contain folder 'Classes'
We should remove the entry `Classes` from here:

https://github.com/dsccommunity/AzureDevOpsDsc/blob/8d43d12989359b8facdf46d86011a34dfe787898/build.yaml#L5-L9

ModuleBuilder will add the classes automatically in the .psm1 file. Now they are duplicated in the folder `Classes`.

### LINKED ISSUE #11: AzureDevOpsDsc: Built module contain folder 'Examples'
We should remove the entry `Examples` from here:

https://github.com/dsccommunity/AzureDevOpsDsc/blob/8d43d12989359b8facdf46d86011a34dfe787898/build.yaml#L5-L9

Examples should be avoided to pass in the built module to minimize the size of the package that is distributed. Examples should be added automatically into the resource conceptual help. 

_DscResource.DocGenerator has as build task for this `Generate_Conceptual_Help` but should be learned how to generate conceptual help for class-based resources if it only know how to do it for MOF-based resource._

### LINKED ISSUE #12: AzureDevOpsDsc: Enums should move out of prefix file
Like 'Classes' enums should be single ps1 files with 1 enum definition per file. Compilation will put them in the main module psm1.
No needs for subfolders in enums. 

https://github.com/dsccommunity/AzureDevOpsDsc/blob/8d43d12989359b8facdf46d86011a34dfe787898/source/prefix.ps1#L13-L28

_As per https://github.com/dsccommunity/AzureDevOpsDsc/pull/7#issuecomment-729941083._

### LINKED ISSUE #25: AzDevOpsProject: Integration tests fails intermittently with timeout error
#### Details of the scenario you tried and the problem that is occurring
Integration tests is throwing a timeout error.

```
      [-] Should not throw when compiling MOF and when calling "Start-DscConfiguration" 11.32s
        Expected no exception to be thrown, but an exception "PowerShell DSC resource AzureDevOpsDsc  failed to execute Set functionality with error message: System.InvalidOperationException: The 'Wait-AzDevOpsOperation' function (using OperationId of '8b09a49e-8e81-44fb-909f-85dcf9f9340e') exceeded specified, maximum timeout (10000 milliseconds). (AZDEVOPSCOMMON0702) " was thrown from D:\a\1\s\tests\Integration\DSCClassResources\AzDevOpsProject.Integration.Tests.ps1:514 char:21
            + ...               Start-DscConfiguration @startDscConfigurationParameters
            +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
        515:                 } | Should -Not -Throw
        at <ScriptBlock>, D:\a\1\s\tests\Integration\DSCClassResources\AzDevOpsProject.Integration.Tests.ps1: line 495
```

#### Verbose logs showing the problem

https://dev.azure.com/dsccommunity/AzureDevOpsDsc/_build/results?buildId=3735&view=logs&j=893fd6d3-ee14-5383-e15d-24a2acc7f145&t=417fa350-1299-5d83-5f55-4c06f3da5c2a&l=866

```
2021-01-26T09:24:10.3197400Z     Context When compiling, applying and testing the MOF - 'AzDevOpsProject_EnsureProjectPresent_Config'
2021-01-26T09:24:10.5639194Z VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = 
2021-01-26T09:24:10.5640109Z SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = 
2021-01-26T09:24:10.5642611Z root/Microsoft/Windows/DesiredStateConfiguration'.
2021-01-26T09:24:10.5649544Z VERBOSE: An LCM method call arrived from computer fv-az124-319 with user sid 
2021-01-26T09:24:10.5651230Z S-1-5-21-4017747932-1028059775-3929666197-500.
2021-01-26T09:24:10.5655992Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Set      ]
2021-01-26T09:24:10.5749029Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Resource ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:10.5753987Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Test     ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:10.5758045Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:10.5759761Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with 0-byte payload
2021-01-26T09:24:10.7236121Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:10.7237268Z 22-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:10.7287484Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] 
2021-01-26T09:24:10.7320843Z DscActionRequired='New'
2021-01-26T09:24:10.7334110Z VERBOSE: [fv-az124-319]: LCM:  [ End    Test     ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]  in 0.1820
2021-01-26T09:24:10.7334812Z  seconds.
2021-01-26T09:24:10.7340163Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Set      ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:10.7484807Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:10.7487306Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with 0-byte payload
2021-01-26T09:24:10.9099464Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:10.9105873Z 22-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:10.9158259Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] 
2021-01-26T09:24:10.9160132Z DscActionRequired='New'
2021-01-26T09:24:10.9218727Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:10.9219342Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with 0-byte payload
2021-01-26T09:24:11.0801777Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:11.0802810Z 22-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:11.0882874Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] POST 
2021-01-26T09:24:11.0883925Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with -1-byte payload
2021-01-26T09:24:11.3340248Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:11.3341256Z 162-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:11.3415900Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:11.3416575Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:11.3417014Z -version=6.0 with 0-byte payload
2021-01-26T09:24:11.5045436Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:11.5047707Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:12.0121636Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:12.0122375Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:12.0122765Z -version=6.0 with 0-byte payload
2021-01-26T09:24:12.2119760Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:12.2120759Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:12.7200008Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:12.7200747Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:12.7201175Z -version=6.0 with 0-byte payload
2021-01-26T09:24:12.8872415Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:12.8873405Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:13.3977501Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:13.3978259Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:13.3978748Z -version=6.0 with 0-byte payload
2021-01-26T09:24:13.5620819Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:13.5621854Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:14.0693079Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:14.0693805Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:14.0694213Z -version=6.0 with 0-byte payload
2021-01-26T09:24:14.2359163Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:14.2360155Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:14.7504652Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:14.7505720Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:14.7506148Z -version=6.0 with 0-byte payload
2021-01-26T09:24:14.9450210Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:14.9453202Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:15.4546631Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:15.4547720Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:15.4548385Z -version=6.0 with 0-byte payload
2021-01-26T09:24:15.6217384Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:15.6219032Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:16.1587637Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:16.1589535Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:16.1590616Z -version=6.0 with 0-byte payload
2021-01-26T09:24:16.3318841Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:16.3319997Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:16.8448676Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:16.8449419Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:16.8449835Z -version=6.0 with 0-byte payload
2021-01-26T09:24:17.0064792Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:17.0066793Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:17.5143439Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:17.5144562Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:17.5145245Z -version=6.0 with 0-byte payload
2021-01-26T09:24:17.7117855Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:17.7119727Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:18.2212789Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:18.2213825Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:18.2214270Z -version=6.0 with 0-byte payload
2021-01-26T09:24:18.3858685Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:18.3860536Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:18.8950177Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:18.8950983Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:18.8951388Z -version=6.0 with 0-byte payload
2021-01-26T09:24:19.0574961Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:19.0575936Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:19.5658928Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:19.5659935Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:19.5660615Z -version=6.0 with 0-byte payload
2021-01-26T09:24:19.7280732Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:19.7281803Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:20.2405988Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:20.2406724Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:20.2407137Z -version=6.0 with 0-byte payload
2021-01-26T09:24:20.4021478Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:20.4022704Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:20.9108316Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:20.9109192Z https://dev.azure.com/azuredevopsdsc/_apis/operations/8b09a49e-8e81-44fb-909f-85dcf9f9340e?includeCapabilities=true&api
2021-01-26T09:24:20.9109797Z -version=6.0 with 0-byte payload
2021-01-26T09:24:21.0728697Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:21.0729332Z 286-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:21.6286853Z VERBOSE: [fv-az124-319]: LCM:  [ End    Set      ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]  in 
2021-01-26T09:24:21.6288895Z 10.9000 seconds.
2021-01-26T09:24:21.6909955Z       [-] Should not throw when compiling MOF and when calling "Start-DscConfiguration" 11.32s
2021-01-26T09:24:21.7420286Z         Expected no exception to be thrown, but an exception "PowerShell DSC resource AzureDevOpsDsc  failed to execute Set functionality with error message: System.InvalidOperationException: The 'Wait-AzDevOpsOperation' function (using OperationId of '8b09a49e-8e81-44fb-909f-85dcf9f9340e') exceeded specified, maximum timeout (10000 milliseconds). (AZDEVOPSCOMMON0702) " was thrown from D:\a\1\s\tests\Integration\DSCClassResources\AzDevOpsProject.Integration.Tests.ps1:514 char:21
2021-01-26T09:24:21.7427696Z             + ...               Start-DscConfiguration @startDscConfigurationParameters
2021-01-26T09:24:21.7436375Z             +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
2021-01-26T09:24:21.7444180Z         515:                 } | Should -Not -Throw
2021-01-26T09:24:21.7451784Z         at <ScriptBlock>, D:\a\1\s\tests\Integration\DSCClassResources\AzDevOpsProject.Integration.Tests.ps1: line 495
2021-01-26T09:24:21.7548755Z VERBOSE: An LCM method call arrived from computer fv-az124-319 with user sid 
2021-01-26T09:24:21.7560628Z S-1-5-21-4017747932-1028059775-3929666197-500.
2021-01-26T09:24:21.7599777Z WARNING: [fv-az124-319]:                            [] The GET operation will be carried against a pending 
2021-01-26T09:24:21.7600601Z configuration since the latest configuration has not converged yet.
2021-01-26T09:24:21.8167250Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Get      ]      
2021-01-26T09:24:21.8427710Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:21.8429311Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with 0-byte payload
2021-01-26T09:24:22.0400724Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:22.0402029Z 331-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:22.0482471Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:22.0483281Z https://dev.azure.com/azuredevopsdsc/_apis/projects/1285b03d-5429-4c14-9804-d5c768742a7b?includeCapabilities=true&api-v
2021-01-26T09:24:22.0484089Z ersion=6.0 with 0-byte payload
2021-01-26T09:24:22.2389956Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:22.2393058Z 1053-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:22.2483525Z VERBOSE: [fv-az124-319]: LCM:  [ End    Get      ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]  in 0.4310
2021-01-26T09:24:22.2484422Z  seconds.
2021-01-26T09:24:22.2519080Z VERBOSE: [fv-az124-319]: LCM:  [ End    Get      ]    in  0.4890 seconds.
2021-01-26T09:24:22.2845026Z       [+] Should not throw when calling "Get-DscConfiguration" 533ms
2021-01-26T09:24:22.6012195Z       [+] Should have set the resource and all the parameters should match 8ms
2021-01-26T09:24:22.6841121Z VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = TestConfiguration,'className' 
2021-01-26T09:24:22.6845278Z = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
2021-01-26T09:24:22.6852430Z VERBOSE: An LCM method call arrived from computer fv-az124-319 with user sid 
2021-01-26T09:24:22.6854156Z S-1-5-21-4017747932-1028059775-3929666197-500.
2021-01-26T09:24:22.6859567Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Test     ]
2021-01-26T09:24:22.6866653Z WARNING: [fv-az124-319]:                            [] The TEST operation will be carried against a pending 
2021-01-26T09:24:22.6868448Z configuration since the latest configuration has not converged yet.
2021-01-26T09:24:22.6957447Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Resource ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:22.6962363Z VERBOSE: [fv-az124-319]: LCM:  [ Start  Test     ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:22.6966556Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:22.6968823Z https://dev.azure.com/azuredevopsdsc/_apis/projects?includeCapabilities=true&api-version=6.0 with 0-byte payload
2021-01-26T09:24:22.8446063Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:22.8447094Z 331-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:22.8509627Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] GET 
2021-01-26T09:24:22.8511334Z https://dev.azure.com/azuredevopsdsc/_apis/projects/1285b03d-5429-4c14-9804-d5c768742a7b?includeCapabilities=true&api-v
2021-01-26T09:24:22.8511718Z ersion=6.0 with 0-byte payload
2021-01-26T09:24:23.0188657Z VERBOSE: [fv-az124-319]:                            [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] received 
2021-01-26T09:24:23.0189649Z 1053-byte response of content type application/json; charset=utf-8; api-version=6.0
2021-01-26T09:24:23.0296472Z VERBOSE: [fv-az124-319]: LCM:  [ End    Test     ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent] True in 
2021-01-26T09:24:23.0298306Z 0.3610 seconds.
2021-01-26T09:24:23.0300575Z VERBOSE: [fv-az124-319]: LCM:  [ End    Resource ]  [[AzDevOpsProject]Integration_Test_EnsureProjectPresent]
2021-01-26T09:24:23.0305246Z VERBOSE: [fv-az124-319]: LCM:  [ End    Test     ]     Completed processing test operation. The operation returned 
2021-01-26T09:24:23.0305868Z True.
2021-01-26T09:24:23.0314061Z VERBOSE: [fv-az124-319]: LCM:  [ End    Test     ]    in  0.4180 seconds.
2021-01-26T09:24:23.0606179Z VERBOSE: Operation 'Invoke CimMethod' complete.
2021-01-26T09:24:23.0612577Z VERBOSE: Time taken for configuration job to complete is 0.459 seconds
2021-01-26T09:24:23.0698400Z       [+] Should return $true when Test-DscConfiguration is run 463ms
2021-01-26T09:24:23.1010658Z 
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

From the integration tests, the configuration `AzDevOpsProject_EnsureProjectPresent_Config`
```powershell
AzDevOpsProject Integration_Test_EnsureProjectPresent
{
    ApiUri              = $Node.ApiUri
    Pat                 = $Node.Pat
    ProjectName         = $Node.ProjectName
    ProjectDescription  = $Node.ProjectDescription
    SourceControlType   = $Node.SourceControlType
    Ensure              = $Node.Ensure
}
```

#### Azure DevOps Server version the target node is running
Azure DevOps Services

#### VSTeam PowerShell modules present on the target node
Not applicable

#### The operating system the target node is running
Microosft Hosted Agent (Azure Pipelines) running the integration tests.

#### Version and build of PowerShell the target node is running
Not applicable

#### Version of the DSC module that was used
Latest `main`

### PR DESCRIPTION
**Pull request by SphenicPaul**
#### Pull Request (PR) description
Includes a number of minor fixes to close some small/minor issues:
 - Increased the default, Azure DevOps API, timeout returned by `Get-AzDevOpsApiWaitTimeoutMs` to 300000 (5 minutes). Also increased related, parameter validation ranges within `Test-AzDevOpsApiTimeoutExceeded`, `Wait-AzDevOpsApiResource` and `Wait-AzDevOpsApiOperation` functions (fixes #25).
 - Updated contextual help (fixes #5).
 - Removed the `Classes` and `Examples` directories from the `build.yaml` so they don't get copied into the module output (fixes #10 and #11).
 - Moved 'Ensure' and 'RequiredAction' enums into 'Enum' directory and out of
    'prefix.ps1' (fixes #12)

#### This Pull Request (PR) fixes the following issues
- Fixes #5
- Fixes #10
- Fixes #11
- Fixes #12
- Fixes #25

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28)

### CODE REVIEW

**Comment by SphenicPaul** [comment]
@johlju - Shout if you've any questions with this. Nothing too major within these changes. 

The integration tests ran OK locally against my Azure DevOps instance so I'd expect them to run OK when merged. Additionally, the API timeout is now 5 minutes so that should resolve the intermittent, integration failures.

I might look at the SQL Server (2019) and Azure DevOps Server (2020) installs (on build server as part of integration tests) for the next PR.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28)* status: all files reviewed, 1 unresolved discussion (waiting on @SphenicPaul)

*[a discussion](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28#-MS9YsA7-BRfTmETOoJJ:-MS9YsA7-BRfTmETOoJK:b6fpm8s) (no related file):*
Now that we are fixing enums, can we remove these?

https://github.com/dsccommunity/AzureDevOpsDsc/blob/48e919e3f9be78154b0b75159239c7ee724b3429/source/Classes/003.AzDevOpsDscResourceBase.ps1#L1-L6

---

**Review by SphenicPaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28#-MS9YsA7-BRfTmETOoJJ:-MS9a2jL2fkobotkQLcR:bmduvi4) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Now that we are fixing enums, can we remove these?

https://github.com/dsccommunity/AzureDevOpsDsc/blob/48e919e3f9be78154b0b75159239c7ee724b3429/source/Classes/003.AzDevOpsDscResourceBase.ps1#L1-L6
</blockquote></details>

Done.

I've added some comments/properties on the three, base classes also. 

---

**Review by SphenicPaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28#-MS9YsA7-BRfTmETOoJJ:-MS9cjrRCPAqorRd3xGe:bnzwa0w) (no related file):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

Done.

I've added some comments/properties on the three, base classes also. 

</blockquote></details>

...and also added comments/headers for the `AzDevOpsProject`class/resource.

---

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/azuredevopsdsc/28#-:-MSBfD5D4dZH57i-Ubxj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SphenicPaul)

**Pull request merged**
